<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Katia Pet Photographer in Tahoe Truckee">
    
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/normalize.css">
    <script src="https://kit.fontawesome.com/f924bf4e1d.js" crossorigin="anonymous"></script>
    <title>Katia Kim Pet Photographer in Truckee Tahoe</title>
</head>
   <body>
      <div class="header">
         <header>
            <div class="title">
               <h1>Katia Kim</h1>
               <h2>Pet Photographer</h2>
            </div>

            <nav>   
               <div id="navBar" class="nav">
                  <div class="dropdown">
                        <a href ="?page=home"><button class="tabButton">Home</button></a>
                        <!--<div class="linkDiv">
                           <a href="#">SousOnglet1-1</a>
                           <a href="#">SousOnglet1-2</a>
                           <a href="#">SousOnglet1-3</a>
                        </div>-->
                  </div>
                  <div class="dropdown">
                     <button class="tabButton">Galleries</button>
                     <div class="linkDiv">
                        <a href="?page=gallery-black-and-white">Black & White</a>
                        <a href="?page=gallery-pets-and-family">Pets and Family</a>
                        <a href="?page=gallery-events">Events</a>
                     </div>
                  </div>
                  <div class="dropdown">
                     <a href="?page=investment"><button class="tabButton">Investment</button></a>
                     <!--<div class="linkDiv">
                        <a href="#">SousOnglet3-1</a>
                        <a href="#">SousOnglet3-2</a>
                        <a href="#">SousOnglet3-3</a>
                     </div>-->
                  </div>

                  <div class="dropdown">
                     <a href="?page=contact"><button class="tabButton">Contact</button></a>
                     <!--<div class="linkDiv">
                        <a href="#">SousOnglet4-1</a>
                        <a href="#">SousOnglet4-2</a>
                        <a href="#">SousOnglet4-3</a>
                     </div>-->
                  </div>
                  <a href="#" class='iconBurger'>&#9776</a>
               </div>
            </nav>
         </header>
      </div>
      <!--<section class="caroussel">SECTION CAROUSSEL-->
      <main>
         <?php require 'router.php' ?>
      </main>

   </body>

   <footer>
      <div class="footer">
         <div class="social">
            <div class="logos">
               <a href="https://www.instagram.com" target="_blank"><i class="fa fa-instagram"></i></a>
               <a href="https://twitter.com/?lang=fr" target="_blank"><i class="fa-brands fa-twitter"></i></a>
               <a href="https://fr-fr.facebook.com" target="_blank"><i class="fa-brands fa-facebook"></i></a>
               <a href="https://www.linkedin.com" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
            </div>
         </div>
         <div class="contact">
            <a href="?page=contact">Contact me</a>
            <div class="adressAndPhone">
               <p>+650 328 456</p>
               <p>728 Oak St </p>
               <p> Truckee CA 96161</p>
            </div>
            <a href="mailto:katia-kim-photos@gmail.com" target="_blank"> katia-kim-photos@gmail.com </a>
         </div>
      </div>
   </footer>
   
<script src="layout.js"></script>

</html>