
   <h3>Tarifs&Infos</h3>
<section class="caroussel">SECTION CAROUSSEL</section>
<h4>Tarifs</h4>
<p>
  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestias tempore ex
  labore? Veniam, commodi veritatis? Nulla veniam laborum harum ipsa perferendis
  iste reiciendis, ea laudantium dolore, corporis alias ratione mollitia
</p>
<h4>Infos</h4>
<p>
  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestias tempore ex
  labore? Veniam, commodi veritatis? Nulla veniam laborum harum ipsa perferendis
  iste reiciendis, ea laudantium dolore, corporis alias ratione mollitia
</p>

<script src="view/js/tarifs.js"></script>