
<h3>Photographies Noir&Blanc</h3>
  <?php foreach($articles as $article) : ?>               
<div class="mainDiv-gallery">

   <div class="nthGalleryDivTitle firstGallery">
      <h4> <?= $article->getName() ?> </h4>
      <img src="../../admin/files/<?= $article->getPhoto() ?>" alt="mainEvenements" />
   </div>
   <?php endforeach; ?>
   
   <div class="gridDiv firstGallery invisible">
      <img src="view/gallery-nb/img/0C25DAA7-346B-452A-A1D6-43F80D79BAD0.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/0EF814C5-EB2B-4FC9-87F7-6B88E7FE7334.jpg" alt="n&b"/>
      <img src="view/gallery-nb/img/5A34C7FC-1C60-4082-A555-AB842A2B225A_1_201_a.jpg" alt="n&b"/>
      <img src="view/gallery-nb/img/6E2B0454-F479-495B-95B2-94F76493F6CC.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/8CAAC5AF-6A17-421F-91F2-BA33F37B9B1D_1_201_a.jpg" alt="n&b"/>
      <img src="view/gallery-nb/img/24F78D13-5B05-437D-8FA8-E565F156C36B.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/48E5D114-B419-4FC0-953B-38DFA41DB860.jpg" alt="n&b"/>
      <img src="view/gallery-nb/img/441C70EE-5ADE-4329-B5DA-1C5816F4DBE7_1_201_a.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/488C09AE-9A95-4DFC-96C8-BBE2CB71B347.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/9071AC2C-13C1-4F7F-ADD3-641E4EC1BF3A_1_201_a.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/66365A81-261B-49EE-89DE-76179721B5BC_1_201_a.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/811080CA-8FAB-4379-849B-D534F3DC45D8.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021060122353988--8751001030558726853-IMG_3124_heic.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021060221260880--583922787028287693-IMG_3272_heic.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021060122365614-2102745881859412003-IMG_3191_heic.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021060312173706-3839793379192995320-IMG_3316_heic.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021072722392372--7502660486932854391-IMG_7448.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/2021092917425536--3761371796285526011-n2wwTSD-0!sizeoriginal.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/A4B4CC97-6687-4836-80AA-018521E15C12.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/APC_2003.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/BA5172C2-5C84-4A74-AE8B-66D4C045D304.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/CFC434C2-36C0-4AC5-A698-41725990E388.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_0703.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_3995.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_4194.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_4216.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_5322.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_5405.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_5498.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_5502.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_5504.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_6920.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/IMG_7713.jpg" alt="n&b" />
      <img src="view/gallery-nb/img/Snapseed.jpg" alt="n&b" />
   </div>
   <input type='button' value='close' class='buttonCloseGallery invisible'>
</div>

<script src="view/js/gallery.js"></script>