<div class="form-container">
  <h2>Espace Admin</h2>
  <form method="post">
    <span class="success"><?= $userMessages['sendSuccess'] ?></span>
      <label for="inputLogin">Login
      <span class="errorMessage"><?= $userMessages['requiredLogin'] ?></span>
      </label>
      <input name="login" id="inputLogin" type="text"/>

      <label for="inputPassword">Mot de passe
      <span class="errorMessage"><?= $userMessages['requiredPassword'] ?></span>
      </label>
      <input name="password" id="inputPassword" type="password" />

      <input type="submit" name="accountSubmit" value="Valider" />
  </form>
</div>
