<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier vos Galleries</title>
</head>
<body>
    // ici formulaire de controle en :POST
        Modifier ->Quelle Gallerie (NB - Animx&Familles - Events)
        dans ctrl : ifIsset choix Gallery & ce choix = NB-->traitement + liaison avec le bonne vue
                                    Else if ce choix = Animx&Familles -->traitement + liaison avec la bonne vue
                                    Else if ce choix = Events -->traitement + liaison avec la bonne vue
                 ->Ajouter un article  (repository : fonction qui add article avec un join sur bonne category)
                 ->Ajouter un titre et une Main photo pour cet article (repository: fonction
                 qui add un nom et une photo avec un join sur l'article )ezfzefazz
              
                 
        Si isset ce formulaire, recup la valeur pour 
        <form action="POST">
            <label for="gallery">Choisis ta gallery: </label>
                <select name="gallery" id="galleryId">

            <?php foreach($gallerys as $gallery): ?>
                <option value = '<?= $gallery->getId() ?>'><?= $gallery->getName() ?></option>
            <?php endforeach; ?>

        </form>

</body>
</html>