<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier vos Galleries</title>
</head>
<body>
   <div class="mainDivForm">
    
        <span class="success"><?= $AdminMessages['sendSuccess'] ?></span>
        <form method="POST" enctype="multipart/form-data">
            <div class="formDiv">
                <label for="gallery">Choisis ta gallery: 
                    <span class="errorMessage"> <?=$AdminMessages['requiredGallery'] ?></span>
                </label>
                <select name="gallerySelect" id="gallery">
                    <?php foreach($gallerys as $gallery) : ?>
                        <option value='<?= $gallery->getId() ?>' > <?= $gallery->getName() ?> </option>
                    <?php endforeach; ?>
                </select>
            </div>  

            <div class="formDiv">
                <label for="inputTitle">Titre d'article 
                    <span class="errorMessage"> <?=$AdminMessages['requiredTitle'] ?></span>
                </label>
                <input type="text" name="inputTitle" id="inputTitle">
            </div>
            <div class="formDiv">
                <label for="inputPhoto">Photo d'entête
                    <span class="errorMessage"> 
                        <?=$AdminMessages['requiredPhoto'] ?>
                        <?=$AdminMessages['wrongExt'] ?>
                    </span>
                </label>
                <input type="file" name="inputPhoto" id="inputPhoto">
            </div>
            <input type="submit" name="submitNewArticle" value="Valider l'Article">
        </form>
        
    </div> 
</body>
</html>