

<?php if (isset($_SESSION['isAdmin']) && ($_SESSION ['isAdmin']===true)) { ?>
         <a href="?page=admin-login" class= "adminLogOut">LogOut</a>
<?php } ?>

<section class="diapo">
   <div class="mainDivCarousel">
      <div class="picturesCarousel">
         <img src="admin/files/KAT_2916-Edit.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/blackNWhiteCats.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/_DSC5093.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/_DSC8092.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/_DSC8190.jpg" alt="carousel picture">
      </div> 
      <div class="picturesCarousel">
         <img src="admin/files/_DSC9766-2.png" alt="carousel picture">
      </div> 
      <div class="picturesCarousel">
         <img src="admin/files/DSC_0869-Edit.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/_DSC6593-Edit-2.jpg" alt="carousel picture">
      </div>
      <div class="picturesCarousel">
         <img src="admin/files/DSC_0190.jpg" alt="carousel picture">
      </div>
      
   </div>
   <i id="leftButton" class="fas fa-chevron-left"></i>
   <i id="rightButton" class="fas fa-chevron-right"></i>
</section> 
<script src="js/carousel.js"></script>