<h3>Accueil</h23>

<section class="caroussel">SECTION CAROUSSEL</section>
   <h3><a href="?page=gallery-famille-animaux">Photographies Animaux</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
      commodi veritatis? Nulla veniam laborum harum ipsa perferendis
      iste reiciendis, ea laudantium dolore, corporis alias ratione
      mollitia
   </p>
   <h3><a href="?page=gallery-evenements">Photographies Evenements</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
       commodi veritatis? Nulla veniam laborum harum ipsa perferendis
       iste reiciendis, ea laudantium dolore, corporis alias ratione
       mollitia
   </p>
   <h3><a href="?page=gallery-nb">Photographies Noir et Blanc</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
      commodi veritatis? Nulla veniam laborum harum ipsa perferendis
      iste reiciendis, ea laudantium dolore, corporis alias ratione
      mollitia
   </p>
   