
<h3>Accueil</h23>

<!--<section class="caroussel">SECTION CAROUSSEL-->
<div class="diapo">
   <div class="next">>></div>
   <div class="elements">
      <div class="element">
         <img src="admin\files\0EF814C5-EB2B-4FC9-87F7-6B88E7FE7334(1).jpg" alt="">
      </div>
      <div class="element">
         <img src="admin\files\KAT_2916-Edit.jpg" alt="">
      </div>
      <div class="element">
         <img src="admin\files\6E2B0454-F479-495B-95B2-94F76493F6CC(1).jpg" alt="">
      </div>
      <div class="element">
         <img src="admin\files\48E5D114-B419-4FC0-953B-38DFA41DB860(1).jpg" alt="">
      </div>
   </div>
</div> 
<!--</section>-->
   <h3><a href="?page=gallery-famille-animaux">Photographies Animaux</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
      commodi veritatis? Nulla veniam laborum harum ipsa perferendis
      iste reiciendis, ea laudantium dolore, corporis alias ratione
      mollitia
   </p>
   <h3><a href="?page=gallery-evenements">Photographies Evenements</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
       commodi veritatis? Nulla veniam laborum harum ipsa perferendis
       iste reiciendis, ea laudantium dolore, corporis alias ratione
       mollitia
   </p>
   <h3><a href="?page=gallery-nb">Photographies Noir et Blanc</a></h3>
   <p>Lorem ipsum dolor sit amet consectetur,
      adipisicing elit. Molestias tempore ex labore? Veniam,
      commodi veritatis? Nulla veniam laborum harum ipsa perferendis
      iste reiciendis, ea laudantium dolore, corporis alias ratione
      mollitia
   </p>
   