
<h3>Accueil</h3>

   <?php require "carousel.phtml" ?>
   
<article class="article aboutMe ">
   <section class="myMisson">
      <h4>Hi, I'm Katia</h4>
      <p>I am a professional pet portrait photographer based in Truckee, CA. Along with my
         rescue dog and bunnies, I feel grateful to call the Greater Lake Tahoe area home. 
         You will most often find me in nature, exploring the trails, or at my local shelter,
         walking homeless dogs.
         I’ve always been fascinated by images and the powerful stories they tell. My love of 
         animals and photography merged when my local shelter asked me to take pictures of their
         adoptable pets. Since then, it became my mission to help proud pet parents capture the beauty,
         joy and spirit of their pets.
      </p>
   </section>
   <section class="myJourney">
      <p>
         I was born and raised in France and growing up, we always had at least a couple of cats 
         and a dog at home.  I’ve always been fascinated by images and the powerful stories they 
         tell and my major in college was Audio and visual technology.My love of animals and photography
         merged when my local shelter asked me to take pictures of their adoptable pets. 
         Since then, it became my mission to help proud pet parents capture the beauty, joy and spirit
         of their pets.
      </p>
   </section>
   <section class="givingBack">
      <h4>Giving Back</h4>
      <p>As an animal lover, I am passionate about giving back. I’ve found the best way for me
         to help animals in need is to donate my photography services to my local shelter. 
         I help them weekly by editing their adoptable pet photos and also by taking pictures of 
         their fundraisers.
         Additionally, I offer end-of-life sessions free of charge. The importance of honoring
         a pet AND making it accessible for all is something  very important to me.
      </p>
   </section>
</article>
   