
<h3>Investment</h3>

<?php require "carousel.phtml" ?>

<article class="investmentArticle">

  <section class="informations">  
    <h3>Informations</h3>
    <p>Hiring a professional pet photographer is an investment, but I believe who you 
      hire should be based on more than just cost analysis. Photographers are visual storytellers.
       Hire someone who tells your story in a way you connect with. Your session will create
        memories that you'll experience for a lifetime and those are priceless.
      I offer a range of session types. Depending on whether you want a full custom private session 
      at a location of your choice to tell your pet's story, a mini-session to get an updated wall 
      portrait or a fun, themed photo for your holiday card - you are sure to find something that
       suits your needs and budget. 
      I do not require minimum orders, prices begin at $30, most private session clients spend
       between $600 and $2000. I offer a range of session types to meet many needs & budgets.
        The private session fee does not include prints or products. Take a look through the 
        different categories to get familiar with the various sessions and product offerings.
      I am based in Truckee, CA and travel to locations approximately an hour (one way) from Truckee.
       If you are interested in an epic location farther than one hour of traveling please 
       <a href="?page=contact" title="contact katia kim pet photographer">contact me </a> for a quote.
    </p>
  </section>
  
  <section class="prices">
    <h4>FULL CUSTOM PRIVATE SESSIONS</h4>
    <div class="sessions">
      <div class="priceByCateg">
        <h5 class="eltWithScrollAnimation">DOGS ON LOCATION</h5>
        <p>Full custom experience, at a park, beach or the comfort of your home! We'll spend 60-90 minutes getting a variety of posed and candid images. Yields approximately 75-125 proofs to choose from. Order from full product line. Tell a full story.
          <span class="price">$225</span>
        </p>
      </div>
      <div class="priceByCateg">
        <h5 class="eltWithScrollAnimation">CATS AT HOME</h5>
        <p>Full custom experience in the comfort of your home! We'll spend 60-90 minutes getting a variety of posed and candid images. Yields approximately 75-125 proofs to choose from. Order from full product line. Tell a full story.
          <span class="price">$225</span>
        </p>
      </div>
      <div class="priceByCateg">
        <h5 class="eltWithScrollAnimation">LOCATION MINI-SESSIONS</h5>
        <p>Minis are 20 minute sessions at pre-determined date and location. Yields ~25 proofs to choose from. Order from limited product line. Ideal for a few updated portraits.
          <span class="price">STARTING AT $125</span>
        </p>
      </div>
      <div class="priceByCateg">
        <h5 class="eltWithScrollAnimation">END-OF-LIFE SESSIONS</h5>
        <p>Memorialize your pet in a special way. We'll spend 60-90 minutes getting a variety of posed and candid images. Yields approximately 75-125 proofs to choose from. Order from full product line.  Memorialize your pet in a special way.
          <span class="price">SESSION FREE OF CHARGE DIGITAL PHOTO GALLERY FREE OF CHARGE
          DONATIONS TO THE <a href ="https://hstt.org/">HUMANE SOCIETY OF TRUCKEE TAHOE </a> 
          WELCOMECUSTOM ARTWORK AT ADDITIONAL CHARGE 
          </span>
        </p>
      </div>
    </div>  
  </section>
  
</article>

<script src="js/investment.js"></script>